apiVersion: apps/v1
kind: Deployment
metadata:
  name: businesslogodesign-web
  labels:
    app: businesslogodesign-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: businesslogodesign-web
  template:
    metadata:
      labels:
        app: businesslogodesign-web
    spec:
      containers:
        - name: businesslogodesign-web
          image: voxtrondocker/businesslogodesign:latest
          ports:
            - containerPort: 80
          imagePullPolicy: Always