apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bld-pvc
  namespace: bld
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard