apiVersion: v1
kind: Service
metadata:
  name: businesslogodesign-web
spec:
  selector:
    app: businesslogodesign-web
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 80
      nodePort: 30005
  type: NodePort